package emu.grasscutter.game.managers.blossom.enums;

public enum BlossomRefreshCondType {
    BLOSSOM_REFRESH_COND_PLAYER_LEVEL_EQUAL_GREATER,
    BLOSSOM_REFRESH_COND_PLAYER_LEVEL_LESS_THAN,
    BLOSSOM_REFRESH_COND_OPEN_STATE,
    BLOSSOM_REFRESH_COND_ACTIVITY_COND,
    BLOSSOM_REFRESH_COND_SCENE_TAG_ADDED
}
